# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'TreatFinder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'GeoFire'
  pod 'Pulley'
  pod 'Cosmos'
  pod 'CodableFirebase'
end
